### ISSUE TITLE
Remove Title

### ISSUE THREAD

**Issue by dewaputrabs** [chrislarsenqlik/SenseBoxPlot#2]
Hi Chris,

I found that your java script is helpful.
but if i want to change the title of the box plot, how can i do it ? is it possible ?

i tried to change in the java script file <SenseBoxplot.js> for this part:
// add a title
				svg.append("text")
			        .attr("x", (width / 2))             
			        .attr("y", 0 + (margin.top / 2))
			        .attr("text-anchor", "middle")  
			        .style("font-size", "18px") 
			        .style("text-decoration", "underline")  
			        .text("Revenue");

into this :
// add a title
				svg.append("text")
			        .attr("x", (width / 2))             
			        .attr("y", 0 + (margin.top / 2))
			        .attr("text-anchor", "middle")  
			        .style("font-size", "18px") 
			        .style("text-decoration", "underline")  
			        .text("Download");
			 
but its didn't work ...
hope anybody can help me out.

thanks

**Comment by chrislarsenqlik** [comment]
That's strange, should work fine. Do you have the javascript debugging console up and have tried a hard reload? Maybe you're looking at a cache?

**Comment by dewaputrabs** [comment]
no i dont have it,
the only thing i have is notepad

how can i do hard reload ? because i already disable the cache

**Comment by dewaputrabs** [comment]
or may you give me the javascript file without the title and the X name ?

**Comment by dewaputrabs** [comment]
hi chris,

i think the problem is for the cache, because once i access the apps from the browser, the changed code in the javascript is detect corectly.

but i think i found another issue about the boxplot calculation.

i will close this issue and open another one.

hope you can assist me in that as well

thank you.
